version: "3.2"
services:
    php:
        build: './docker/php/'
        depends_on:
        - mysql
        volumes:
        - ./:/srv/app:rw,cached
        networks:
        - backend
    apache:
        build: './docker/apache/'
        depends_on:
        - php
        - mysql
        networks:
        - frontend
        - backend
        volumes:
        - ./public:/srv/app/public:ro
        ports:
        - "8080:80"
    mysql:
        #build: './docker/mysql/'
        build: './docker/mysql/'
        volumes:
        - ./docker/mysql/datas:/var/lib/mysql
        ports:
        - "4306:3306"
        networks:
        - backend
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_user_password
networks:
    frontend:
    backend:
